In [1]:
conda install numpy

^C

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3, 4, 5])

In [6]:
my_2darray = ([1,2,3,4],[5,6,7,8])

In [7]:
my_2darray

([1, 2, 3, 4], [5, 6, 7, 8])

In [8]:
my_array[1]

2

In [9]:
my_array[0:2]

array([1, 2])

In [10]:
my_2darray[0:2]

([1, 2, 3, 4], [5, 6, 7, 8])

In [11]:
my_2darray[:0]

()

In [12]:
my_2darray[:1,0]

TypeError: tuple indices must be integers or slices, not tuple

In [13]:
my_2darray[:,0]

TypeError: tuple indices must be integers or slices, not tuple

In [14]:
my_2darray[0:1]

([1, 2, 3, 4],)

In [15]:
my_array>2

array([False, False,  True,  True,  True])

In [16]:
my_array*2

array([ 2,  4,  6,  8, 10])

In [18]:
my_array + np.array([5,6,7,8,9])

array([ 6,  8, 10, 12, 14])

In [19]:
my_array.shape

(5,)

In [21]:
np.append(my_array, [11,12,13,14,15])

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])

In [25]:
np.append(my_array,7)

array([1, 2, 3, 4, 5, 7])

In [26]:
np.append(my_array,0,7)

AxisError: axis 7 is out of bounds for array of dimension 1

In [27]:
my_array

array([1, 2, 3, 4, 5])

In [28]:
np.delete(my_array, [0])

array([2, 3, 4, 5])

In [29]:
np.mean(my_array)

3.0

In [30]:
np.median(my_array)

3.0

In [31]:
my_array.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [32]:
np.std(my_array)

1.4142135623730951

In [44]:
student_list = [1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]

In [48]:
student_array = np.array(student_list)

In [51]:
student_array[0]

array([1, 2, 3, 4, 5])

In [52]:
student_array.shape

(3, 5)

In [54]:
student_array.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12],
       [13, 14, 15]])

In [55]:
student_array[:,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [56]:
student_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [59]:
arr = np.arange(0,10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[3:]=100

In [62]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [63]:
arr = np.arange(1,10,step=2)

In [64]:
arr

array([1, 3, 5, 7, 9])

In [71]:
arr = np.linspace(1,100,70)

In [72]:
arr

array([  1.        ,   2.43478261,   3.86956522,   5.30434783,
         6.73913043,   8.17391304,   9.60869565,  11.04347826,
        12.47826087,  13.91304348,  15.34782609,  16.7826087 ,
        18.2173913 ,  19.65217391,  21.08695652,  22.52173913,
        23.95652174,  25.39130435,  26.82608696,  28.26086957,
        29.69565217,  31.13043478,  32.56521739,  34.        ,
        35.43478261,  36.86956522,  38.30434783,  39.73913043,
        41.17391304,  42.60869565,  44.04347826,  45.47826087,
        46.91304348,  48.34782609,  49.7826087 ,  51.2173913 ,
        52.65217391,  54.08695652,  55.52173913,  56.95652174,
        58.39130435,  59.82608696,  61.26086957,  62.69565217,
        64.13043478,  65.56521739,  67.        ,  68.43478261,
        69.86956522,  71.30434783,  72.73913043,  74.17391304,
        75.60869565,  77.04347826,  78.47826087,  79.91304348,
        81.34782609,  82.7826087 ,  84.2173913 ,  85.65217391,
        87.08695652,  88.52173913,  89.95652174,  91.39

In [73]:
arr1 = arr.copy()

In [74]:
arr1

array([  1.        ,   2.43478261,   3.86956522,   5.30434783,
         6.73913043,   8.17391304,   9.60869565,  11.04347826,
        12.47826087,  13.91304348,  15.34782609,  16.7826087 ,
        18.2173913 ,  19.65217391,  21.08695652,  22.52173913,
        23.95652174,  25.39130435,  26.82608696,  28.26086957,
        29.69565217,  31.13043478,  32.56521739,  34.        ,
        35.43478261,  36.86956522,  38.30434783,  39.73913043,
        41.17391304,  42.60869565,  44.04347826,  45.47826087,
        46.91304348,  48.34782609,  49.7826087 ,  51.2173913 ,
        52.65217391,  54.08695652,  55.52173913,  56.95652174,
        58.39130435,  59.82608696,  61.26086957,  62.69565217,
        64.13043478,  65.56521739,  67.        ,  68.43478261,
        69.86956522,  71.30434783,  72.73913043,  74.17391304,
        75.60869565,  77.04347826,  78.47826087,  79.91304348,
        81.34782609,  82.7826087 ,  84.2173913 ,  85.65217391,
        87.08695652,  88.52173913,  89.95652174,  91.39

In [77]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [79]:
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [83]:
np.random.rand(5,3)

array([[0.60181235, 0.26741793, 0.66993543],
       [0.55230445, 0.61095479, 0.61759719],
       [0.7446742 , 0.91619374, 0.40460295],
       [0.47925774, 0.82412498, 0.11932773],
       [0.53733862, 0.24443168, 0.01937278]])